# dbt profile yaml file with multiple environments
mph-ga4-site:
 target: dev
 outputs:
  dev:
   type: bigquery
   method: oauth
   project: nomadic-archway-344500
   dataset: mph_analytics_dev
   threads: 1
   timeout_seconds: 300
   location: US
   priority: interactive
   retries: 1
  prod:
   type: bigquery
   method: oauth
   project: nomadic-archway-344500
   dataset: mph_analytics_prod
   threads: 5
   timeout_seconds: 300
   location: US
   priority: interactive
   retries: 1