# Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "mph_ga4_site"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "mph_ga4_site"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# Run on start
on-run-start:
    - "{{ create_udfs() }}"

# Variables
vars:
    start_date: "2021-01-01"
    execution_date: "notset"
    dataset_udf: "_utils"

# Model config
models:
    mph_ga4_site:
        marts:
            core:
                materialized: table
                +dataset: core
                +tags:
                    - "core"
                    - "daily"
            marketing:
                materialized: table
                +dataset: marketing
                +tags:
                    - "marketing"
                    - "daily"
        staging:
            google_analytics:
                materialized: view
                +dataset: staging
                +tags:
                    - "staging"
                    - "daily"